apiVersion: v1
kind: Service
metadata:
  name: mangos-account-creation
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: mangos-account-creation
  sessionAffinity: None
  type: NodePort